POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "profile": {
        "email": "jane@gmail.com",
        "name" : "Jane Doe",
        "imageUrl": "none",
        "atSign" : "@Jane"
    }
}

### 
GET http://localhost:8000/users/

###

DELETE  http://localhost:8000/auth/logout