POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "profile": {
        "email": "john@gmail.com",
        "name" : "John Doe",
        "imageUrl": "none",
        "atSign" : "John"
    }
}

###

GET http://localhost:8000/tweets/latest

###
GET http://localhost:8000/tweets/followed

###
GET http://localhost:8000/users/followedUsers

###
GET http://localhost:8000/users/getId

###
POST http://localhost:8000/users/follow
Content-Type: application/json

{
    "uidToFollow": 1
}

###
POST http://localhost:8000/tweets/post
Content-Type: application/json

{
    "profile": {
        "email": "john@gmail.com",
        "name" : "John Doe",
        "imageUrl": "none",
        "atSign" : "John"
    },
    "post": "Hello guys"
}

###

GET http://localhost:8000/auth

###

DELETE  http://localhost:8000/auth/logout